// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkTQqSU8DqWmWXRDz85vJR-d6IzeHviis',
    appId: '1:922420393675:web:136f407d1c00f237698d4e',
    messagingSenderId: '922420393675',
    projectId: 'wv-authantication-app',
    authDomain: 'wv-authantication-app.firebaseapp.com',
    storageBucket: 'wv-authantication-app.appspot.com',
    measurementId: 'G-QWMMNFBQSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhIJuIiCvwuPHa2SmRsWQa1V-6raDRuq4',
    appId: '1:922420393675:android:37b4f58b8c4a1105698d4e',
    messagingSenderId: '922420393675',
    projectId: 'wv-authantication-app',
    storageBucket: 'wv-authantication-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsWJaOeK0gI5azlV7uqTPHnmkokbVJKYY',
    appId: '1:922420393675:ios:99fbe7bde79b2315698d4e',
    messagingSenderId: '922420393675',
    projectId: 'wv-authantication-app',
    storageBucket: 'wv-authantication-app.appspot.com',
    iosBundleId: 'com.example.authanticationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsWJaOeK0gI5azlV7uqTPHnmkokbVJKYY',
    appId: '1:922420393675:ios:99fbe7bde79b2315698d4e',
    messagingSenderId: '922420393675',
    projectId: 'wv-authantication-app',
    storageBucket: 'wv-authantication-app.appspot.com',
    iosBundleId: 'com.example.authanticationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkTQqSU8DqWmWXRDz85vJR-d6IzeHviis',
    appId: '1:922420393675:web:1b4276b6ce7b407a698d4e',
    messagingSenderId: '922420393675',
    projectId: 'wv-authantication-app',
    authDomain: 'wv-authantication-app.firebaseapp.com',
    storageBucket: 'wv-authantication-app.appspot.com',
    measurementId: 'G-ERB1T9CNSG',
  );
}
