// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1hNSM220GipVCEWKqv5ph6wEaCH3nxBw',
    appId: '1:12118280772:web:3bc44922b70119f4c78a11',
    messagingSenderId: '12118280772',
    projectId: 'wv-chat-app',
    authDomain: 'wv-chat-app.firebaseapp.com',
    storageBucket: 'wv-chat-app.appspot.com',
    measurementId: 'G-0E12FQH9NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnSeabC-4geZAertNYn-yeg8sIJIZwIW8',
    appId: '1:12118280772:android:bace2d13f32e1eabc78a11',
    messagingSenderId: '12118280772',
    projectId: 'wv-chat-app',
    storageBucket: 'wv-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBycnRQyLbqizWXP6gVrPvbcBoaJXjv9Uk',
    appId: '1:12118280772:ios:cfb521dee80fffbbc78a11',
    messagingSenderId: '12118280772',
    projectId: 'wv-chat-app',
    storageBucket: 'wv-chat-app.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBycnRQyLbqizWXP6gVrPvbcBoaJXjv9Uk',
    appId: '1:12118280772:ios:cfb521dee80fffbbc78a11',
    messagingSenderId: '12118280772',
    projectId: 'wv-chat-app',
    storageBucket: 'wv-chat-app.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1hNSM220GipVCEWKqv5ph6wEaCH3nxBw',
    appId: '1:12118280772:web:0b8a422891c2cf41c78a11',
    messagingSenderId: '12118280772',
    projectId: 'wv-chat-app',
    authDomain: 'wv-chat-app.firebaseapp.com',
    storageBucket: 'wv-chat-app.appspot.com',
    measurementId: 'G-64GS1DCR0H',
  );
}
